name: everydone_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  flutter_launcher_icons: ^0.7.5

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  custom_switch:
  flutter_picker:
  datetime_picker_formfield:
  numberpicker: ^1.1.0
  firebase_core: 0.4.0+8
  firebase_storage: 3.0.4
  image_cropper: 1.0.2
  image_picker: 0.6.0+17
  cloud_firestore: ^0.12.9+4
  rflutter_alert: ^1.0.3
  flutter_tts: ^0.9.0
  bubble_bottom_bar: ^1.2.0
  bottom_navy_bar: ^5.3.2
  intl: ^0.15.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-app.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
